### ISSUE TITLE
Missing Play Icon on albums

### ISSUE THREAD

**Issue by nxllxvxxd** [tedhinklater/finality#47]
![2024-07-20 03 18 59,800](https://github.com/user-attachments/assets/a59521e7-c90f-4a45-bd6e-7311f12b35e5)
When hovering over an allbum the play button is missing as well as the button has a rather large area below the image that can be clicked

EDIT:
I don't know if you can but throwing the idea out there to make it another button like the ones along the edges

**Comment by tedhinklater** [comment]
The play/shuffle/favorite/watched/3-dot icons don't move position between movie posters (tall), episode pictures (short/wide) or album covers (square).

They are all the same width, so the constant is the top edge. I could rearrange the icons to all be on the top? 

Basically, when the play arrow was visible, it was in the middle of the movie poster, but that means it's below the episode picture and in the bottom-middle of album covers (not good). That's why I decided to just make it a play "area" rather than arrow.

![play1](https://github.com/user-attachments/assets/1fd71f64-b61c-4a86-ac77-0ca1532aa569)

But as you've seen it's not perfect, it means there's a play area below the album

![play2](https://github.com/user-attachments/assets/3feb35cc-cb53-42d6-b1b2-bb676d96cbe9)

You think they should be all visible along the top?

**Comment by nxllxvxxd** [comment]
I would think maybe just adding the play button to the top would be okay to help keep the icons dispersed unless I am being slow and not realizing you can't do that, I'm just throwing shit at the wall and hoping it sticks here, tell me to fuck off if I ever get too annoying lmao

**Comment by tedhinklater** [comment]
Nah I was cutting corners and it didn't adapt to different media, had to hide buttons etc. Should be all good now.
